# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
  drupal-app:
    image: custom-drupal
    ports:
      - "8080:80"
    build: .
    volumes: 
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
     
  postgresql:
    image: postgres:9.6
    environment: 
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes: 
      - drupal-data:/var/lib/postgresql/data


volumes: 
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
